# Generated by Django 4.2.4 on 2023-09-07 09:51

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_name', models.CharField(max_length=100)),
                ('auther', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/Category/')),
            ],
        ),
        migrations.CreateModel(
            name='enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_contact', models.CharField(max_length=10)),
                ('user_course', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default='')),
                ('description', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pro_image', models.ImageField(upload_to='images/Product/')),
                ('Duration', models.CharField(default='', max_length=100)),
                ('startDate', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='TopCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('Duration', models.CharField(max_length=100)),
                ('startDate', models.DateField()),
                ('product_img', models.ImageField(upload_to='images/TopProducts/')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField()),
                ('features', ckeditor.fields.RichTextField()),
                ('requirement', ckeditor.fields.RichTextField()),
                ('duration', models.TextField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EduApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Addmission_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('d_o_b', models.DateField()),
                ('address', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=100)),
                ('qualfication', models.CharField(default='', max_length=100)),
                ('work_experience', models.CharField(default='', max_length=100)),
                ('course_price', models.FloatField(default='')),
                ('Documents', models.FileField(upload_to='')),
                ('Information', models.CharField(default='', max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduApp.product')),
            ],
        ),
    ]
